// new-frontend/src/shared/components/problems/AttemptVerdict.tsx
import { useMemo } from 'react';
import { Chip, ChipProps, Tooltip } from '@mui/material';

export enum Verdicts {
  InQueue = -2,
  Running,
  JudgementFailed,
  Accepted,
  WrongAnswer,
  TimeLimitExceeded,
  RuntimeError,
  OutputFormatError,
  MemoryLimitExceeded,
  Rejected,
  CompilationError,
  CommandExecutingError,
  IdlenessLimitExceeded,
  SyntaxError,
  CheckerNotFound,
  OnlyPython,
  ObjectNotFound,
  FakeAccepted,
  PartialSolution,
  NotAvailableLanguage,
  Hacked,
}

export type VerdictKey = Verdicts;

interface AttemptVerdictProps extends Omit<ChipProps, 'label' | 'color'> {
  verdict?: VerdictKey;
  title: string;
  testCaseNumber?: number | null;
  balls?: number | null;
}

const verdictColorMap: Record<VerdictKey, ChipProps['color']> = {
  [Verdicts.InQueue]: 'warning',
  [Verdicts.Running]: 'secondary',
  [Verdicts.JudgementFailed]: 'default',
  [Verdicts.Accepted]: 'success',
  [Verdicts.WrongAnswer]: 'error',
  [Verdicts.TimeLimitExceeded]: 'error',
  [Verdicts.RuntimeError]: 'error',
  [Verdicts.OutputFormatError]: 'warning',
  [Verdicts.MemoryLimitExceeded]: 'error',
  [Verdicts.Rejected]: 'error',
  [Verdicts.CompilationError]: 'error',
  [Verdicts.CommandExecutingError]: 'error',
  [Verdicts.IdlenessLimitExceeded]: 'error',
  [Verdicts.SyntaxError]: 'error',
  [Verdicts.CheckerNotFound]: 'default',
  [Verdicts.OnlyPython]: 'default',
  [Verdicts.ObjectNotFound]: 'default',
  [Verdicts.PartialSolution]: 'warning',
  [Verdicts.NotAvailableLanguage]: 'default',
  [Verdicts.FakeAccepted]: 'success',
  [Verdicts.Hacked]: 'error',
};

const verdictShortTitle: Record<VerdictKey, string> = {
  [Verdicts.InQueue]: 'InQ',
  [Verdicts.Running]: 'Run',
  [Verdicts.JudgementFailed]: 'JF',
  [Verdicts.Accepted]: 'AC',
  [Verdicts.WrongAnswer]: 'WA',
  [Verdicts.TimeLimitExceeded]: 'TL',
  [Verdicts.RuntimeError]: 'RE',
  [Verdicts.OutputFormatError]: 'PE',
  [Verdicts.MemoryLimitExceeded]: 'ML',
  [Verdicts.Rejected]: 'RJ',
  [Verdicts.CompilationError]: 'CE',
  [Verdicts.CommandExecutingError]: 'CEE',
  [Verdicts.IdlenessLimitExceeded]: 'IL',
  [Verdicts.SyntaxError]: 'SE',
  [Verdicts.CheckerNotFound]: '',
  [Verdicts.OnlyPython]: '',
  [Verdicts.ObjectNotFound]: '',
  [Verdicts.PartialSolution]: '',
  [Verdicts.NotAvailableLanguage]: '',
  [Verdicts.FakeAccepted]: 'AC',
  [Verdicts.Hacked]: '',
};

const hideTestCaseFor: VerdictKey[] = [
  Verdicts.Accepted,
  Verdicts.InQueue,
  Verdicts.Running,
  Verdicts.JudgementFailed,
  Verdicts.Rejected,
  Verdicts.CheckerNotFound,
  Verdicts.OnlyPython,
  Verdicts.PartialSolution,
  Verdicts.FakeAccepted,
  Verdicts.Hacked,
];

const AttemptVerdict = ({
  verdict,
  title,
  testCaseNumber,
  balls,
  ...rest
}: AttemptVerdictProps) => {
  const color =
    verdict !== undefined && verdictColorMap[verdict] ? verdictColorMap[verdict] : 'default';
  const shortTitleRaw = verdict !== undefined ? verdictShortTitle[verdict as VerdictKey] : '';
  const shortTitle = shortTitleRaw || title;
  const showTestCase =
    typeof testCaseNumber === 'number' &&
    testCaseNumber > 0 &&
    !(hideTestCaseFor as number[]).includes((verdict ?? 0) as number);
  const showBall = verdict === Verdicts.PartialSolution && balls !== undefined && balls !== null;

  const label = useMemo(() => {
    const parts = [shortTitle];
    if (showTestCase) parts.push(`#${testCaseNumber}`);
    if (showBall) parts.push(String(balls));
    return parts.join(' ').trim();
  }, [shortTitle, showTestCase, testCaseNumber, showBall, balls]);

  return (
    <Tooltip title={title}>
      <Chip
        size="medium"
        variant="outlined"
        color={color}
        label={label}
        sx={{ fontWeight: 700 }}
        {...rest}
      />
    </Tooltip>
  );
};

export default AttemptVerdict;

// angular-frontend/src/app/shared/components/attempt-verdict/attempt-verdict.component.ts
import { Component, Input, OnChanges, SimpleChanges } from '@angular/core';
import { Verdicts } from '@problems/constants';
import { NgbTooltipModule } from '@ng-bootstrap/ng-bootstrap';

const testCaseHideVerdicts = [
  Verdicts.Accepted,
  Verdicts.InQueue,
  Verdicts.Rejected,
  Verdicts.JudgementFailed,
  Verdicts.CheckerNotFound,
  Verdicts.PartialSolution,
  Verdicts.Hacked,
];

function getVerdictColor(verdict: Verdicts) {
  const verdictColors = {
    [Verdicts.Accepted]: 'success',
    [Verdicts.FakeAccepted]: 'success',
    [Verdicts.JudgementFailed]: 'dark',
    [Verdicts.CheckerNotFound]: 'dark',
    [Verdicts.InQueue]: 'warning',
    [Verdicts.Running]: 'secondary',
    [Verdicts.PartialSolution]: 'warning',
  };
  return verdictColors[verdict] || 'danger';
}


function getShortTitle(verdict: Verdicts) {
  return {
    [Verdicts.InQueue]: 'InQ',
    [Verdicts.Running]: 'Run',
    [Verdicts.JudgementFailed]: 'JF',
    [Verdicts.Accepted]: 'AC',
    [Verdicts.WrongAnswer]: 'WA',
    [Verdicts.RuntimeError]: 'RE',
    [Verdicts.TimeLimitExceeded]: 'TL',
    [Verdicts.OutputFormatError]: 'PE',
    [Verdicts.MemoryLimitExceeded]: 'ML',
    [Verdicts.Rejected]: 'RJ',
    [Verdicts.CompilationError]: 'CE',
    [Verdicts.CommandExecutingError]: 'CEE',
    [Verdicts.IdlenessLimitExceeded]: 'IL',
    [Verdicts.SyntaxError]: 'SE',
    [Verdicts.CheckerNotFound]: '',
    [Verdicts.OnlyPython]: '',
    [Verdicts.ObjectNotFound]: '',
    [Verdicts.FakeAccepted]: 'AC',
    [Verdicts.PartialSolution]: '',
    [Verdicts.NotAvailableLanguage]: '',
    [Verdicts.Hacked]: '',
  }[verdict];
}


@Component({
  selector: 'attempt-verdict',
  standalone: true,
  imports: [
    NgbTooltipModule
  ],
  templateUrl: './attempt-verdict.component.html',
  styleUrl: './attempt-verdict.component.scss'
})
export class AttemptVerdictComponent implements OnChanges {
  @Input({required: true}) verdict: Verdicts;
  @Input() title: string;
  @Input() testCaseNumber: number;
  @Input() balls: number;

  public showTestCaseNumber = true;
  public showBall = true;
  public verdictColor: string;
  public shortTitle: string;

  ngOnChanges(changes: SimpleChanges) {
    this.showTestCaseNumber = (this.testCaseNumber > 0 && testCaseHideVerdicts.indexOf(this.verdict) === -1);
    this.showBall = (this.verdict === Verdicts.PartialSolution);
    this.verdictColor = getVerdictColor(this.verdict);
    this.shortTitle = getShortTitle(this.verdict);
  }
}

<span [ngbTooltip]="title" class="border-1 text-fixed-white badge bg-outline-{{ verdictColor }}">
  {{ shortTitle || title }}

  @if (showTestCaseNumber) {
    #{{ testCaseNumber }}
  }

  @if (showBall) {
    {{ balls }}
  }
</span>
